# Generated by Django 6.1.1 on 2026-09-08 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad_carga', models.DecimalField(decimal_places=2, help_text='Capacidad en kg', max_digits=10)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En viaje', 'En viaje'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_origen', models.CharField(max_length=150)),
                ('ciudad_destino', models.CharField(max_length=150)),
                ('fecha_hora_salida', models.DateTimeField()),
                ('fecha_hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('tipo_carga', models.CharField(max_length=100)),
                ('kilometraje_inicial', models.PositiveIntegerField(default=0)),
                ('kilometraje_final', models.PositiveIntegerField(blank=True, null=True)),
                ('combustible_inicial', models.DecimalField(blank=True, decimal_places=2, help_text='Litros al inicio', max_digits=8, null=True)),
                ('combustible_final', models.DecimalField(blank=True, decimal_places=2, help_text='Litros al finalizar', max_digits=8, null=True)),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En curso', 'En curso'), ('Finalizado', 'Finalizado')], default='Programado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='transporte.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='transporte.vehiculo')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros_cargados', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ciudad', models.CharField(max_length=150)),
                ('fecha_carga', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='transporte.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='transporte.vehiculo')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='transporte.viaje')),
            ],
            options={
                'verbose_name': 'Carga de Combustible',
                'verbose_name_plural': 'Cargas de Combustible',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
