# Generated by Django 5.2.8 on 2026-09-17 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_add_mantenimiento_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidente', models.CharField(choices=[('Falla Mecánica', 'Falla Mecánica'), ('Retraso en Vía', 'Retraso en Vía'), ('Pinchazo Neumático', 'Pinchazo Neumático'), ('Desvío por Derrumbe', 'Desvío por Derrumbe'), ('Derrame de Lubricante', 'Derrame de Lubricante'), ('Accidente de Tránsito', 'Accidente de Tránsito'), ('Robo o Hurto', 'Robo o Hurto'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('lugar', models.CharField(max_length=200)),
                ('fecha_incidente', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Reportado', 'Reportado'), ('En Revisión', 'En Revisión'), ('Resuelto', 'Resuelto')], default='Reportado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='transporte.viaje')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha_incidente'],
            },
        ),
        migrations.CreateModel(
            name='Viatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[('Peajes', 'Peajes'), ('Hospedaje', 'Hospedaje'), ('Alimentación', 'Alimentación'), ('Parqueadero', 'Parqueadero'), ('Lavado de unidad', 'Lavado de unidad'), ('Desvare menor', 'Desvare menor'), ('Otro', 'Otro')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Valor en COP', max_digits=14)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('fecha_gasto', models.DateField()),
                ('estado', models.CharField(choices=[('En validación', 'En validación'), ('Aprobado', 'Aprobado'), ('Reembolsado', 'Reembolsado'), ('Rechazado', 'Rechazado')], default='En validación', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaticos', to='transporte.conductor')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaticos', to='transporte.viaje')),
            ],
            options={
                'verbose_name': 'Viático',
                'verbose_name_plural': 'Viáticos',
                'ordering': ['-fecha_gasto'],
            },
        ),
    ]
