# Generated by Django 6.1.1 on 2026-09-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_incidente_viatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='cargacombustible',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargacombustible',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='combustible/', verbose_name='Foto / Comprobante'),
        ),
        migrations.AddField(
            model_name='cargacombustible',
            name='observacion_admin',
            field=models.TextField(blank=True, verbose_name='Observación de Administración'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='incidentes/', verbose_name='Foto de Evidencia'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='respuesta_admin',
            field=models.TextField(blank=True, verbose_name='Respuesta / Dictamen Administrativo'),
        ),
        migrations.AddField(
            model_name='viatico',
            name='comprobante_foto',
            field=models.ImageField(blank=True, null=True, upload_to='viaticos/', verbose_name='Comprobante / Factura'),
        ),
        migrations.AddField(
            model_name='viatico',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viatico',
            name='observacion_admin',
            field=models.TextField(blank=True, verbose_name='Observación de Auditoría'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='estado',
            field=models.CharField(choices=[('Reportado', 'Reportado'), ('En Revisión', 'En Revisión'), ('Resuelto', 'Resuelto'), ('Rechazado', 'Rechazado')], default='Reportado', max_length=20),
        ),
    ]
